# name for the workflow
# need space for key value pair
name: CI for Go code
# on is for event triggering like push, commit etc
on:
  push:
  # which branch to monitor, can add more than one branch to monitor by using comma within []
    branches: [main]
  pull_request:
    branches: [main]

# jobs to execute
jobs:
  # build to specify name of the job
  build:
    # name for printing
    name: Load OS
    # runs-on to specify OS in virtual machine
    runs-on: ubuntu-latest
    # steps to run after OS is set up on VM
    steps:
    - name: Print hello
      # run is to run command prompt/ terminal, | used for multiple lines
      run: |
        ls
        echo Hello!!
        
    # set up Go    
    - name: Setup Go
      # uses install the software you want from actions/ repo
      uses: actions/setup-go@v3.2.0
      # with is like a customisation command
      with:
        go-version: 1.18
        
    # check Go version
    - name: Check Go version
      run: go version
      
    # clone repo to root of VM
    - name: Checkout Repo
      uses: actions/checkout@v2.4.2
      
    # check if files are corrected cloned
    - name: Check File System
      run: ls
      
    # install go dependencies and run test
    # go mod init calc
    # go get dependecncies
    # go mod tidy
    # can be replaced by 
    # go build
    - name: Install Go Dependencies and Run Test
      run: |
        go build
        go test -v
